DROP TABLE DAY_CHG;
DROP TABLE DAY;
DROP TABLE CHG_NUM;

CREATE TABLE CHG_NUM (
	CHG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CHG_CODE VARCHAR(255),
	CHG_DESC VARCHAR(255),
	CHG_TYPE VARCHAR(266)
);
CREATE TABLE DAY (
	DAY_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DATE_ID DATETIME
);
CREATE TABLE DAY_CHG(
	UNIQUE_CHG_ID INTEGER PRIMARY KEY AUTOINCREMENT,
	DAY_ID DECIMAL(12),
	HOURS DOUBLE,
	CHG_ID DECIMAL(12),
	FOREIGN KEY (CHG_ID) REFERENCES CHG_NUM(CHG_ID),
	FOREIGN KEY(DAY_ID) REFERENCES DAY(DAY_ID)
);
