SELECT  SUM(HOURS) AS total_charging
FROM CHG_NUM 
JOIN DAY_CHG 
ON CHG_NUM.CHG_ID = DAY_CHG.CHG_ID 
WHERE CHG_CODE = 'CHGTOOL';

SELECT DATE_ID, CHG_DESC
FROM DAY_CHG
JOIN DAY ON DAY_CHG.DAY_ID = DAY.DAY_ID
JOIN CHG_NUM ON DAY_CHG.CHG_ID = CHG_NUM.CHG_ID
WHERE DATE_ID BETWEEN DATE('2021-03-01') AND DATE('2021-03-03')
ORDER BY DATE_ID;